-dontwarn lib.kalu.avselector.**
-keep class lib.kalu.avselector.Selector{*;}
-keep class lib.kalu.avselector.SelectionCreator{*;}
-keep class lib.kalu.avselector.ui.selector.SelectorActivity{*;}
-keep class lib.kalu.avselector.ui.priview.PreviewAllActivity{*;}
-keep class lib.kalu.avselector.ui.priview.PreviewSelectorActivity{*;}